# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

stages:
  - build
  - test
  - testcheck
  - deploy
  - package

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
   
after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"
   
build1:
  tags:
   - arm_mcu
  stage: build
  script:
    - scons
  cache:
    untracked: true
    
filetest1:
  tags:
   - arm_mcu_shell
  stage: test
  script: 
    - file target/* > result1.txt
    - cat result1.txt
    - mv result1.txt ./target
  cache:
    untracked: true
filetest2:
  tags:
   - arm_mcu_shell
  stage: test
  script: 
    - file target/* > result2.txt
    - cat result2.txt
    - mv result2.txt ./target
  cache:
    untracked: true
testcheck1:
  tags:
   - arm_mcu_shell
  stage: testcheck
  script: 
    - echo "Do another parallel test here"
    - echo "For example run a lint test"
    - ls ./target
    - ls ./src
    - ls ./Drivers
    - cat ./target/result1.txt
    - cat ./target/result2.txt
  cache:
    untracked: true
    policy: pull
deploy1:
  tags:
   - arm_mcu_shell
  stage: deploy
  script:
    - echo "Do your deploy here"

pack-gz:
  tags:
   - arm_mcu_shell
  stage: package
  script:
    - GZIP=-9 tar czvf packaged.tar.gz ./target/
    - ls
  cache:
    untracked: true
    policy: pull
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - target/
      - packaged.tar.gz
    expire_in: 10 minutes  
